theme: "hugo-PaperMod"
baseURL: http://frankmuraca.netlify.app
languageCode: en-us
title: Frank Muraca
enableEmoji: true


menu:
  main:
    - name: "About"
      url: "/about/"
      weight: 1
    - name: "Blog"
      url: "/"
      weight: 2

params:
    ShowShareButtons: true
    
    homeInfoParams:
        Title: Hi there! Welcome to my blog about neighborhoods & housing ğŸ¡ Disaster recovery â˜” Community-driven data ğŸ“Š

    socialIcons: # optional
        - name: "github"
          url: "https://github.com/frankmuraca"
        - name: "twitter"
          url: "https://twitter.com/FrankMuraca"
        - name: "email"
          url: "mailto:fhmuraca@gmail.com"