theme: "hugo-PaperMod"
baseURL: http://frankmuraca.netlify.app
languageCode: en-us
title: Frank Muraca
subtitle: Neighborhoods & housing ğŸ¡ Disaster recovery â˜” Community-driven data ğŸ“Š
enableEmoji: true


menu:
  main:
    - name: "About"
      url: "/about/"
      weight: 1
    - name: "Blog"
      url: "/"
      weight: 2

params:
    ShowShareButtons: true
    